/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.hypermetro;

public class Main {

    public static void main(String[] args) {
        System.out.print("Hello world!");
    }
}
